apiVersion: v1
kind: Pod
metadata:
  name: multi-container #pod name
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
  - name: alma
    image: "almalinux:9"
    command: "sleep 2000"
