apiVersion: v1
kind: Pod
metadata:
  name: environment-var
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    env:
    - name: course
      value: 'Kubernetes'
    - name: Duration
      value: '20hours'
