apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests: #this is soft limit means this is the minimum value of resources requested
        memory: "128Mi"
        cpu: "100m"
      limits: #this is hard limit, means max limit of resources which cannot be exceeded.. limits should be atleast one or more than requests.. if this value exceeds containers will not run
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
