apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
    - name: course
      valueFrom:
        configMapKeyRef: #this refers config map values from 08-config-map.yaml .. so that this pod doesnt need any update if config value changes, only configmap can be updated and that reflects here also
          name: daws78s 
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef: 
          name: daws78s
          key: Trainer 
