apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector: # below values are given as labels in 12-nginx.yaml...So this service identifies which pod to be called using these selectors
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #this is service port
    targetPort: 80  #this is nginx server port.. means pod port
