apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms: #this will match with the node labels we created in command line.. check notes
        - matchExpressions:
          - key: project
            operator: In
            values:
            - expense
  containers:
  - name: with-node-affinity
    image: nginx
  tolerations: # this is also added here because we already gave taint to that node, so we had to add toleratins section.. otherwise if only labels were given to pod, and no taint is added.. we dont need tolerations section here
  - key: "project"
    operator: "Equal"
    value: "expense"
    effect: "NoSchedule"
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"