#this is admin task, admin creates storage class and we can use that in 02-ebs-dynamic.yaml.. 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-ebs
reclaimPolicy: Retain #check notes for more info on reclaim policy
provisioner: ebs.csi.aws.com # info of drivers installed
volumeBindingMode: WaitForFirstConsumer